### ISSUE TITLE
Unable to install mobile-core because of oc variables

### ISSUE THREAD

**Issue by leathersole** [aerogear/mobile-core#1]
## Description
Unable to install mobile-core because of oc variables

## Environment

*Operating system*: macOS 10.13.2
*OpenShift versions*:  v3.7.0+7ed6862

## Steps to reproduce
Follow this instruction
https://github.com/aerogear/mobile-core/blob/master/docs/walkthroughs/local-setup.adoc#creating-a-local-cluster

## Actual result
mobile-core/installer/playbook.yml failed at this task:

```
TASK [openshift-origin-client-tools : download...] ********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{oc_checksums[oc_ver][oc_sha][oc_platform]}}: 'dict object' has no attribute u'v3.7.0-rc.0'\n\nThe error appears to have been in '/Users/tkonishi/.ansible/roles/openshift-origin-client-tools/tasks/main.yml': line 23, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: download...\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: {{oc_checksums[oc_ver][oc_sha][oc_platform]}}: 'dict object' has no attribute u'v3.7.0-rc.0'"}
```

## Workaround
Remove these lines at mobile-core/installer/vars/mobile-control-panel.yml

```
oc_ver: v3.7.0-rc.0                                                                                                                                                              
oc_sha: 'e92d5c5'
oc_checksums:
  linux-64bit: sha256:e35e53b42a00e4d04305ec55c94b623135d3ac236c999c00765703161da23769
  mac: sha256:0f1ec8ad4e84a207e54d526c27daa73bd066f75f14d8f735377132da04acb959
```

After modified, the playbook passed the task, but failed at `oc-cluster-up` task.
